[project]
name = "jojo-out"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "ruff>=0.9.6",
    "streamlit>=1.42.0",
]
